### ISSUE TITLE
youre dumbass fr

### ISSUE THREAD

**Issue by bbambiku** [Qoft/medal-nitro-gen#1]
skidding someone's work is gay, yk?

**Comment by TheBlackCookie** [comment]
bro skids so funny on god

**Comment by bbambiku** [comment]
it isnt better lmfao, the original globy have proxy support and multithreading. (and its open sourced)

**Comment by TheBlackCookie** [comment]
> it isnt better lmfao, the original globy have proxy support and multithreading. (and its open sourced)

I still cant understand what is there to crack in a open source project 🧠

**Comment by Qoft** [comment]
> it isnt better lmfao, the original globy have proxy support and multithreading. (and its open sourced)

the code better. not the gen itself
