### ISSUE TITLE
issue with proxies?

### ISSUE THREAD

**Issue by imB3tter** [Qoft/medal-nitro-gen#3]
i keep getting this error "HTTPSConnectionPool(host='medal.tv', port=443): Max retries exceeded with url: /api/authentication (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))" and i am wondering if there is an issue with my proxies or the code?

**Comment by UnrealBloxy** [comment]
Please check if your proxy is working properly. Pretty sure, there is an issue with the proxy

**Comment by kekeds** [comment]
> 

shit proxies ong

**Comment by Qoft** [comment]
shit proxies ong
