### ISSUE TITLE
Skidded from Globy

### ISSUE THREAD

**Issue by skidghoul** [Qoft/medal-nitro-gen#4]
Same Variables, Imports

**Comment by timof121** [comment]
![b71ad766ff](https://user-images.githubusercontent.com/52547763/180603918-6d7a8413-b542-4b26-96ca-33fc7d47575c.gif)

**Comment by Qoft** [comment]
> Same Variables, Imports

LOL

**Comment by kekeds** [comment]
> Same Variables, Imports

LOLOLLOLOOL

**Comment by skidghoul** [comment]
> > Same Variables, Imports
> 
> LOLOLLOLOOL

🤡

**Comment by skidghoul** [comment]
![image](https://user-images.githubusercontent.com/107319782/182260871-a8c09a75-ce89-43db-9a10-394af5a40587.png)
You skidded the software qoft skidded 💀

**Comment by Qoft** [comment]
bro u guys still care this barely works anymore 😂

**Comment by kekeds** [comment]
> > > Same Variables, Imports
> > 
> > 
> > LOLOLLOLOOL
> 
> 🤡

![image](https://user-images.githubusercontent.com/107649934/182274827-54022493-b570-443d-b5c3-e9e18f24eddd.png)

YOU HAVE THE SAME SHIT XDDD

**Comment by skidghoul** [comment]
> > > > Same Variables, Imports
> > > 
> > > 
> > > LOLOLLOLOOL
> > 
> > 
> > 🤡
> 
> ![image](https://user-images.githubusercontent.com/107649934/182274827-54022493-b570-443d-b5c3-e9e18f24eddd.png)
> 
> YOU HAVE THE SAME SHIT XDDD

Look at the source code, fucking bum 🤣

**Comment by skidghoul** [comment]
> > > > > Same Variables, Imports
> > > > 
> > > > 
> > > > LOLOLLOLOOL
> > > 
> > > 
> > > 🤡
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/107649934/182274827-54022493-b570-443d-b5c3-e9e18f24eddd.png)
> > YOU HAVE THE SAME SHIT XDDD
> 
> Look at the source code, fucking bum 🤣

Dont Skid It Though 😄
